name: Pruebas

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Instalar dependencias
        run: npm ci
        
      - name: Verificar tipos de TypeScript
        run: npx tsc --noEmit
      
      - name: Ejecutar pruebas
        run: npm test